name: CI Build and Publish â€“ Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  ci-release:
    uses: ./.github/workflows/ci-build-publish.yml
    secrets:
      AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
      AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
      HMCTS_CP_ADO_PAT: ${{ secrets.HMCTS_CP_ADO_PAT }}
      PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
    with:
      is_release: true
      is_publish: true
      trigger_docker: true
      trigger_deploy: true
      pacticipant: CPCourtScheduleProvider
      pact_ignore: true
      pact_env: dev/pactTest
